from codelets import Datatype

OP_LOCATIONS = {"OBUF": 0, "IBUF": 1, "VMEM": 2, "IMM": 3, "EXTMEM": 4}
SIMD_OP_READ_NS = ["OBUF", "VMEM", "IMM"]
SIMD_OP_WRITE_NS = ["IBUF", "VMEM", "IMM"]
SIMD_NS = ["OBUF", "IBUF", "VMEM", "IMM"]

GENESYS_CFG = {}
GENESYS_CFG['ARRAY_N'] = 32
GENESYS_CFG['ARRAY_M'] = 32
GENESYS_CFG['DATA_WIDTH'] = 8 // 8
GENESYS_CFG['WGT_WIDTH'] = 8 // 8
GENESYS_CFG['BIAS_WIDTH'] = 32 // 8
GENESYS_CFG['ACC_WIDTH'] = 32 // 8
GENESYS_CFG['SIMD_WIDTH'] = 32
GENESYS_CFG['CHANNEL_BW'] = 512 // 8

GENESYS_CFG['IBUF_DEPTH'] = 2048
GENESYS_CFG['WBUF_DEPTH'] = 512
GENESYS_CFG['OBUF_DEPTH'] = 2048
GENESYS_CFG['BBUF_DEPTH'] = 2048
GENESYS_CFG['IMM_DEPTH'] = 1
GENESYS_CFG['DRAM_DEPTH'] = 100000
GENESYS_CFG['VMEM_DEPTH'] = GENESYS_CFG['OBUF_DEPTH']


GENESYS_CFG['WBUF_BANKS'] = GENESYS_CFG['ARRAY_M'] * GENESYS_CFG['ARRAY_N']
GENESYS_CFG['OBUF_BANKS'] = GENESYS_CFG['ARRAY_M']
GENESYS_CFG['BBUF_BANKS'] = GENESYS_CFG['ARRAY_M']
GENESYS_CFG['VMEM_BANKS'] = GENESYS_CFG['SIMD_WIDTH']
GENESYS_CFG['DRAM_BANKS'] = 1


OP_DTYPES = [Datatype(type='FXP', bitwidth=8), Datatype(type='FXP', bitwidth=16), Datatype(type='FXP', bitwidth=32),
             Datatype(type='FP', bitwidth=16), Datatype(type='FP', bitwidth=32)]

SIMD_OPCODE_BITWIDTH = 4
SIMD_FNCODE_BITWIDTH = 4
NS_BITWIDTH = 5
NS_IDX_BITWIDTH = 3

from .genesys import generate_genesys, define_genesys
